//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_Platform_for_Spices
{
    public partial class Payment
    {
        protected global::System.Web.UI.HtmlControls.HtmlImage imgOrderProduct;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblOrderName;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblOrderWeight;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblSubtotal;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblTotal;
        protected global::System.Web.UI.WebControls.TextBox txtFullName;
        protected global::System.Web.UI.WebControls.TextBox txtMobile;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        protected global::System.Web.UI.WebControls.HiddenField hdnPaymentMethod;
        protected global::System.Web.UI.WebControls.Button btnPlaceOrder;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMobile;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revMobile;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAddress;
    }
}
