//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_Platform_for_Spices
{
    public partial class Products
    {
    }
}
