//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_Platform_for_Spices
{
    public partial class ViewOrder
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblOrderNumber;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblOrderDate;
        protected global::System.Web.UI.HtmlControls.HtmlImage imgViewOrderProduct;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblViewOrderName;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblViewOrderWeight;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblViewOrderPrice;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblViewName;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblViewMobile;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblViewEmail;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblViewAddress;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblViewPayment;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblViewSubtotal;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblViewTotal;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblViewOrderDate;
    }
}
