//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_Platform_for_Spices
{
    public partial class ViewProduct
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblBreadcrumbName;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblBadge;
        protected global::System.Web.UI.HtmlControls.HtmlImage imgProduct;
        protected global::System.Web.UI.WebControls.Label lblWeightBox;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblCategory;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblProductName;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblTagline;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblDesc;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblSource;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblGrade;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblPrice;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor btnBuyNow;
    }
}
